CREATE FUNCTION TRAER_ANIOS(PID NUMBER) RETURN NUMBER
IS
MI_RETORNO NUMBER:=0;
BEGIN
    BEGIN
    SELECT YEARS INTO MI_RETORNO
    FROM JOB_YEARS
    WHERE EMPLOYEE_ID= PID;
    RETURN MI_RETORNO;
    EXCEPTION
    WHEN NO_DATA_FOUND THEN MI_RETORNO := 0;
    END;
END;

CREATE FUNCTION TRAER_DIAS(PID NUMBER) RETURN NUMBER
IS
MI_RETORNO NUMBER:=0;
BEGIN
    BEGIN
    SELECT NUM_DAYS INTO MI_RETORNO
    FROM NUM_DAYS
    WHERE EMPLOYEE_ID= PID;
    RETURN MI_RETORNO;
    EXCEPTION
    WHEN NO_DATA_FOUND THEN MI_RETORNO := 0;
    END;
END;

CREATE FUNCTION TRAER_SALARIO(PID NUMBER) RETURN NUMBER
IS
MI_RETORNO NUMBER:=0;
BEGIN
    BEGIN
    SELECT SALARY INTO MI_RETORNO
    FROM EMPLOYEES
    WHERE EMPLOYEE_ID= PID;
    RETURN MI_RETORNO;
    EXCEPTION
    WHEN NO_DATA_FOUND THEN MI_RETORNO := 0;
    END;
END;

CREATE FUNCTION SOY_JEFE(PID NUMBER) RETURN NUMBER
IS
MI_RETORNO NUMBER := 0;
BEGIN
    BEGIN
    SELECT 1 INTO MI_RETORNO
    FROM EMPLOYEES E, JOBS J
    WHERE E.EMPLOYEE_ID = PID
    AND (E.JOB_ID LIKE '%MGR%'
    OR E.JOB_ID LIKE '%MAN%')
    AND E.JOB_ID = J.JOB_ID;
    EXCEPTION
    WHEN NO_DATA_FOUND THEN MI_RETORNO := 0;
    END;
RETURN MI_RETORNO;
END;

CREATE OR REPLACE PROCEDURE CAL_SUB(PID NUMBER, PSB OUT EMPLOYEES.SALARY%TYPE)
IS 
BEGIN
PSB := (TRAER_SALARIO(PID)/30) * TRAER_DIAS(PID);
END;
/

DECLARE 
MI_SB NUMBER;
BEGIN
    CAL_SUB(202, MI_SB);
    DBMS_OUTPUT.PUT_LINE('SALARIO BASE ' || MI_SB);
END;
/